### ISSUE TITLE
Write tests for grammar

### ISSUE THREAD

**Issue by schan219** [schan219/lang#2]
TODO:
* Variable declaration
* Function declaration
* Function call

We need to be able to write multiple variable and/or function declarations, and multiple function calls in main.

**Comment by shade** [comment]
In regards to multiple function calls in main, there's only 1 real function call. If you want to do multiple calls it's done via some sort of logical operation, e.g. AND/OR, ex: calling 3 functions `fn1`, `fn2`, and `fn3`

```
(main (and (fn1 0) (fn2 0) (fn3 0))))
```

**Comment by schan219** [comment]
Yes, I think I am mistaken about multiple function calls being a problem. There are still some grammar issues (and some of them have just been discovered) but I will create a new issue and close this one since the corresponding pull request has been merged.
